const LokacijeOpstina = [
  {
    ime: "Gračanica",
    lokacija: [
      "Badovac",
      "Batuse",
      "Gornja Gušterica",
      "Gračanica",
      "Dobrotin",
      "Donja Gušterica",
      "Kišnica",
      "Laplje Selo",
      "Lepina",
      "Livađe",
      "Preoce",
      "Radevo",
      "Skulanevo",
      "Suvi Do",
      "Sušica",
      "Ugljare",
      "Čaglavica",
    ],
  },
  {
    ime: "Zubin Potok",
    lokacija: [
      "Babiće",
      "Babudovica",
      "Banja",
      "Bojnoviće",
      "Brnjak",
      "Bube",
      "Burlate",
      "Velika Kaludra",
      "Velji Breg",
      "Vitakovo",
      "Vojmisliće",
      "Vrba",
      "Vukojeviće",
      "Vukosavljeviće",
      "Gazivode",
      "Gornje Varage",
      "Gornji Jasenovik",
      "Gornji Strmac",
      "Dobroševina",
      "Donje Varage",
      "Donji Jasenovik",
      "Dragalica",
      "Drainoviće",
      "Dren",
      "Žarevi",
      "Zagrađe",
      "Zagulje",
      "Zečeviće",
      "Zubin Potok",
      "Zupče",
      "Jabuka",
      "Jagnjenica",
      "Junake",
      "Kijevce",
      "Klečke",
      "Kobilja Glava",
      "Kovače",
      "Kozarevo",
      "Kopiloviće",
      "Krligate",
      "Ledenik",
      "Lučka Reka",
      "Mala Kaludra",
      "Međeđi Potok",
      "Oklace",
      "Padine",
      "Paruci",
      "Prevlak",
      "Prelez",
      "Preseka",
      "Pridvorica",
      "Rančiće",
      "Rezala",
      "Rujište",
      "Tušiće",
      "Ugljare",
      "Crepulja",
      "Čabra",
      "Čečevo",
      "Češanoviće",
      "Čitluk",
      "Šipovo",
      "Štuoce",
    ],
  },
  {
    ime: "Peć",
    lokacija: [
      "Alagina Reka",
      "Babiće",
      "Barane",
      "Belo Polje",
      "Blagaje",
      "Boge",
      "Crni Vrh",
      "Brestovik",
      "Brežanik",
      "Broluć",
      "Bučane",
      "Velika Jablanica",
      "Veliki Štupelj",
      "Vitomirica",
      "Vragovac",
      "Glavičica",
      "Glođane",
      "Goraždevac",
      "Grabovac",
      "Dobri Do",
      "Drelje",
      "Dubočak",
      "Dubovo",
      "Duganjive",
      "Zagrmje",
      "Zahać",
      "Zlopek",
      "Jablanica",
      "Krstovac",
      "Klinčina",
      "Košutane",
      "Kosurić",
      "Kotradić",
      "Kruševac",
      "Kućište",
      "Lipa",
      "Labljane",
      "Laz Belopać",
      "Ložane",
      "Lugađija",
      "Lođa",
      "Lješane",
      "Ljevoša",
      "Ljubenić",
      "Ljutoglava",
      "Mala Jablanica",
      "Mali Štupelj",
      "Maljeviće",
      "Milanovac",
      "Nabrđe",
      "Naklo",
      "Nepolje",
      "Novo Selo",
      "Osoje",
      "Ozrim",
      "Plavljane",
      "Peć",
      "Pepiće",
      "Pištane",
      "Počešće",
      "Radavac",
      "Romune",
      "Rašić",
      "Raušić",
      "Rosulje",
      "Ruhot",
      "Svrke",
      "Siga",
      "Trebović",
      "Trstenik",
      "Turjak",
      "Ćuška",
      "Hadžovići",
      "Čelopek",
      "Škrele",
    ],
  },
  {
    ime: "Leposavić",
    lokacija: [
      "Bare",
      "Belo Brdo",
      "Beluće",
      "Berberište",
      "Bistrica",
      "Borova",
      "Borčane",
      "Brzance",
      "Vitanoviće",
      "Vračevo",
      "Vuča",
      "Gnježdane",
      "Gornji Krnjin",
      "Graničane",
      "Grkaje",
      "Guvnište",
      "Gulije",
      "Desetak",
      "Dobrava",
      "Donje Isevo",
      "Donji Krnjin",
      "Dren",
      "Duboka",
      "Zabrđe",
      "Zavrata",
      "Zemanica",
      "Zrnosek",
      "Ibarsko Postenje",
      "Jarinje",
      "Jelakce",
      "Jošanica",
      "Kajkovo",
      "Kamenica",
      "Kijevčiće",
      "Koporiće",
      "Kostin Potok",
      "Košutica",
      "Košutovo",
      "Kruševo",
      "Kruščica",
      "Kutnje",
      "Lazine",
      "Leposavić",
      "Lešak",
      "Lozno",
      "Majdevo",
      "Mekiniće",
      "Miokoviće",
      "Mioliće",
      "Mošnica",
      "Ostraće",
      "Plakaonica",
      "Planinica",
      "Popovce",
      "Potkomlje",
      "Pridvorica",
      "Rvatska",
      "Rodelj",
      "Rucmance",
      "Seoce",
      "Slatina",
      "Sočanica",
      "Tvrđan",
      "Trebiće",
      "Trikose",
      "Ćirkoviće",
      "Ulije",
      "Ceranja",
      "Crveni",
      "Crnatovo",
      "Šaljska Bistrica",
      "Šarpelj",
    ],
  },
  {
    ime: "Zvečan",
    lokacija: [
      "Banov Do",
      "Banjska",
      "Banjska Reka",
      "Banjski Suvi Do",
      "Boljetin",
      "Bresnica",
      "Valač",
      "Veliko Rudare",
      "Vilište",
      "Grabovac",
      "Grižani",
      "Doljane",
      "Žaža",
      "Žerovnica",
      "Žitkovac",
      "Zvečan",
      "Izvori",
      "Jankov Potok",
      "Joševik",
      "Kamenica",
      "Korilje",
      "Kula",
      "Lipa",
      "Lipovica",
      "Lovac",
      "Lozište",
      "Lokva",
      "Mali Zvečan",
      "Malo Rudare",
      "Matica",
      "Meki Do",
      "Oraovica",
      "Rudine",
      "Sendo",
      "Srbovac",
    ],
  },
  {
    ime: "Gnjilane",
    lokacija: [
      "Bilince",
      "Brasaljce",
      "Brnjica",
      "Bukovik",
      "Velekince",
      "Vladovo",
      "Vlaštica",
      "Vrapčić",
      "Gadiš",
      "Goden",
      "Gornje Kusce",
      "Gornje Slakovce",
      "Gornji Livoč",
      "Gornji Makreš",
      "Gumnište",
      "Dobrčane",
      "Donja Budriga",
      "Donje Slakovce",
      "Donji Livoč",
      "Donji Makreš",
      "Draganac",
      "Dunavo",
      "Žegovačka Vrbica",
      "Žegovac",
      "Žegra",
      "Inatovce",
      "Kišno Polje",
      "Kmetovačka Vrbica",
      "Kmetovce",
      "Koretište",
      "Kravarica",
      "Kuredž",
      "Lipovica",
      "Lovce",
      "Mališevo",
      "Mozgovo",
      "Mučibaba",
      "Nosalje",
      "Paralovo",
      "Parteš",
      "Pasjak",
      "Pasjane",
      "Pidić",
      "Podgrađe",
      "Poneš",
      "Prilepnica",
      "Selište",
      "Sapar",
      "Slubica",
      "Stančić",
      "Stanišor",
      "Straža",
      "Stublina",
      "Terzijaj",
      "Ugljare",
      "Hadžaj",
      "Cernica",
      "Čelik",
      "Šilovo",
      "Šurlane",
    ],
  },
  {
    ime: "Štrpce",
    lokacija: [
      "Berevce",
      "Brezovica",
      "Brod",
      "Viča",
      "Vrbeštica",
      "Gornja Bitinja",
      "Gotovuša",
      "Donja Bitinja",
      "Drajkovce",
      "Ižance",
      "Jažince",
      "Koštanjevo",
      "Sevce",
      "Sušice",
      "Firača",
      "Štrpce",
    ],
  },
  {
    ime: "Kosovska Mitrovica",
    lokacija: ["Kosovska Mitrovica", "Gornji Suvi Do", "Donji Suvi Do"],
  },
];

export default LokacijeOpstina;
